name: Version Workflow
run-name: Version 
on: 
  workflow_call:
    inputs:
      azure_storage_account:
        type: string
        description: the azure storage account 
        required: true
      table_name:
        type: string
        description: The table name
        required: true  
      environment:
        type: string
        required: true
    outputs:
      next_version: 
        value: ${{ jobs.get-version.outputs.next_version }}

env:
  AZURE_STORAGE_AUTH_MODE: login
  azure_storage_account: frontenddeployments
  AZ_VERSION: latest
  ENVIRONMENT: ${{ inputs.environment }}
  ROW_KEY: current
      
jobs:
  get-version:
    runs-on: ubuntu-latest
    name: Get the next version 
    outputs:
      next_version: ${{ steps.outputs.next_version }}
    steps:
      - name: Get current version
        uses: azure/CLI@v1
        with:
          azcliversion: ${{ env.AZ_VERSION }}
          inlineScript: |
            currentVersion=$(az storage entity show --partition-key ${{ env.ENVIRONMENT }} --row-key ${{ env.ROW_KEY }} --table-name ${{ inputs.TABLE_NAME}} --query Version)
            echo "CURRENT_VERSION=$currentVersion" >> "$GITHUB_ENV"
      - name: Set next version
        shell: pwsh
        run: |
          $currentVersion = ${{ env.CURRENT_VERSION }}
          $versionObj = [System.Version]::Parse($currentVersion)
          $nextVersion = "$($versionObj.Major).$($versionObj.Minor).$($versionObj.Build + 1)"
          echo "next_version=$nextVersion" >> $env:GITHUB_OUTPUT

