name: Interact with Azure ressources via OIDC
concurrency: test

on:
  push:
    branches:
      - "test/*"

permissions:
  id-token: write
  contents: read
    
jobs:
  frontend:
    uses: ./.github/workflows/reuseable-deployment-workflow.yml
    with:
      environment: test
  summery:
    runs-on: ubuntu-latest
    needs: frontend
    steps:
      - name: Generate summery
        run: |
          echo "### Deployment of ${{ needs.frontend.outputs.next_version }}! to test environment :rocket:" >> $GITHUB_STEP_SUMMARY

