name: Interact with Azure ressources via OIDC

on:
  push:
    branches:
      - "test/*"
      - main
  
jobs:
  find-environment:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.prod.outputs.env_name || steps.test.outputs.env_name }}
      
    steps:
      - name: production environment
        id: prod
        if: ${{ github.ref_name == 'main' }}
        run: echo "env_name=prod" >> $GITHUB_OUTPUT
      - name: test environment
        id: test
        if: ${{ github.ref_name != 'main' }}
        run: echo "env_name=test" >> $GITHUB_OUTPUT

  frontend:
    needs: find-environment
    permissions:
      id-token: write
      contents: read
    concurrency: ${{ needs.find-environment.outputs.env_name }}
    uses: ./.github/workflows/reuseable-deployment-workflow.yml
    with:
      environment: ${{ needs.find-environment.outputs.env_name }}
      azure_storage_account: frontenddeployments
  frontend-sync-prod-to-test:
    permissions:
      id-token: write
      contents: read
    name: Sync production code to test environment 
    if: ${{ needs.find-environment.outputs.env_name == 'prod' }}
    needs: 
      - find-environment
      - frontend
    concurrency: test
    uses: ./.github/workflows/reuseable-deployment-workflow.yml
    with:
      environment: test
      azure_storage_account: frontenddeployments
      override_version: ${{ needs.frontend.outputs.next_version }}
  summery:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs:
      - find-environment
      - frontend
    steps:
      - name: create prod release
        if: ${{ needs.find-environment.outputs.env_name == 'prod' }}
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.repos.createRelease({ owner: context.repo.owner, repo: context.repo.repo, tag_name: "v${{ needs.frontend.outputs.next_version }}", generate_release_notes: true });
      - name: Generate summery
        run: |
          echo "### Deployment of ${{ needs.frontend.outputs.next_version }} to ${{ needs.find-environment.outputs.env_name }} environment :rocket:" >> $GITHUB_STEP_SUMMARY

