name: Interact with Azure ressources via OIDC

on:
  push:
    branches:
      - "test/*"
      - main

permissions:
  id-token: write
  contents: read
    
jobs:
  find-environment:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.prod.outputs.env_name || steps.test.outputs.env_name }}
      
    steps:
      - name: production environment
        id: prod
        if: ${{ github.ref_name == 'main' }}
        run: echo "env_name=prod" >> $GITHUB_OUTPUT
      - name: test environment
        id: test
        if: ${{ github.ref_name != 'main' }}
        run: echo "env_name=test" >> $GITHUB_OUTPUT

  frontend:
    needs: find-environment
    concurrency: ${{ needs.find-environment.outputs.env_name }}
    uses: ./.github/workflows/reuseable-deployment-workflow.yml
    with:
      environment: ${{ needs.find-environment.outputs.env_name }}
      azure_storage_account: frontenddeployments
  summery:
    runs-on: ubuntu-latest
    needs:
      - find-environment
      - frontend
    steps:
      - name: Generate summery
        run: |
          echo "### Deployment of ${{ needs.frontend.outputs.next_version }} to ${{ needs.find-environment.outputs.env_name }} environment :rocket:" >> $GITHUB_STEP_SUMMARY

