name: Test github action variables
permissions: write-all

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Use Variable
        run: |
          echo "Awesome variable: ${{ vars.AWESOME_VARIABLE }}"
      - name: Update vars variable 
        uses: actions/github-script@v6
        with:
          script: |
            const requestUri = "https://api.github.com/repos/" + context.repo.owner + "/" + context.repo.repo + "/actions/variables/AWESOME_VARIABLE";
            console.log(requestUri);
            await fetch(requestUri, {
              method: "PATCH",
              headers: {
                Authorization: "token ${{ secrets.VARIABLES_TOKEN }}"
              }
            });
            await github.request(requestUri, {
              name: "AWESOME_VARIABLE",
              value: "test-${{ github.run_id }}"
            });
